abstract final class RouteNames {
  static const auth = '/auth';
  static const authLogin = '/auth/login';
  static const authSignup = '/auth/signup';
  static const authPhysicalInformation = '/auth/physical-information';
  static const authGoalSelection = '/auth/goal-selection';
  static const authForgotPassword = '/auth/forgot-password';
  static const onboard = '/onboard';
  static const main = '/main';
  static const meals = '/meals';
  static const mealSearch = '/meals/search';
  static const water = '/water';
  static const ai = '/ai';
  static const explore = '/explore';
  static const more = '/more';
  static const profile = '/more/profile';
  static const goals = '/more/goals';
  static const progress = '/more/progress';
  static const reminders = '/more/reminders';
  static const connectedApps = '/more/connected-apps';
  static const settings = '/more/settings';
  static const helpSupport = '/more/help-support';
}
