// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7HLwvxplzxmTlS-ErrKlefAAGbEwDhyI',
    appId: '1:725422523899:web:bf3c8b4ab35db10ee4775e',
    messagingSenderId: '725422523899',
    projectId: 'nutrivision-7e139',
    authDomain: 'nutrivision-7e139.firebaseapp.com',
    storageBucket: 'nutrivision-7e139.firebasestorage.app',
    measurementId: 'G-4RX59YWZMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-Rhzby2CjgugoGsEFQyjBlTCTOmpobo',
    appId: '1:725422523899:android:82290f9988df8c9ce4775e',
    messagingSenderId: '725422523899',
    projectId: 'nutrivision-7e139',
    storageBucket: 'nutrivision-7e139.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpLMF8ccuFIJdL3AIEnsqYhQDjkdbRRs',
    appId: '1:725422523899:ios:a49fc3e0f6dd997ae4775e',
    messagingSenderId: '725422523899',
    projectId: 'nutrivision-7e139',
    storageBucket: 'nutrivision-7e139.firebasestorage.app',
    iosClientId: '725422523899-vqsoutnvt1isiihdao6h0l4l1bggtfhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.afia',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpLMF8ccuFIJdL3AIEnsqYhQDjkdbRRs',
    appId: '1:725422523899:ios:a49fc3e0f6dd997ae4775e',
    messagingSenderId: '725422523899',
    projectId: 'nutrivision-7e139',
    storageBucket: 'nutrivision-7e139.firebasestorage.app',
    iosClientId: '725422523899-vqsoutnvt1isiihdao6h0l4l1bggtfhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.afia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7HLwvxplzxmTlS-ErrKlefAAGbEwDhyI',
    appId: '1:725422523899:web:9a541011a97473f1e4775e',
    messagingSenderId: '725422523899',
    projectId: 'nutrivision-7e139',
    authDomain: 'nutrivision-7e139.firebaseapp.com',
    storageBucket: 'nutrivision-7e139.firebasestorage.app',
    measurementId: 'G-G9KTD8RZG4',
  );
}
